name: GuiAPI
version: '0.0-BETA'
main: Mystix.GuiAPI.GuiAPI
api-version: '1.21'
load: STARTUP
authors: [RocraftYT]

commands:
  GuiPack:
    usage: /GuiPack
    permission: Gui.Manager
  Serialize:
    usage: /Serialize
    permission: Gui.Manager